Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -692,6 +692,11 @@ jobs:
           #Remove Abi Exports and Error
           rm -rf ./common/android/abi_gki_protected_exports_*
           perl -pi -e 's/^\s*"protected_exports_list"\s*:\s*"android\/abi_gki_protected_exports_aarch64",\s*$//;' ./common/BUILD.bazel
+
+          if grep -q -- '-dirty' ./common/scripts/setlocalversion; then
+            echo "Error: -dirty detected in setlocalversion"
+            exit 1
+          fi
         fi
 
         #git config --global user.name "TheWildJames"
