fix(ci): update kernel patch conditions in build workflow
Modify the build workflow to include additional kernel version checks and apply corresponding patches. The changes ensure proper compatibility with different kernel sublevels by adjusting uid checks in susfs.c and adding a new condition for sublevel 41 or lower.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -203,7 +203,14 @@ jobs:
             elif [ "${{ inputs.ksu_commit }}" == "pershoot" ]; then
               curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/dev-susfs/kernel/setup.sh" | bash -s dev-susfs
               cd KernelSU-Next
-              git restore --source=5aad87b3c6319330d6991ba4c937e44e50fe16f5^ -- kernel/Kbuild
+              COMMIT_HASH=$(git log --grep="kernel: Allow building when KSU_SUSFS is unset" -n 1 --format=%H)
+              if [ -n "$COMMIT_HASH" ]; then
+                echo "Found commit $COMMIT_HASH, restoring kernel/Kbuild..."
+                git restore --source="${COMMIT_HASH}^" -- kernel/Kbuild
+              else
+                echo "Commit not found"
+                exit 1
+              fi
             elif [ -n "${{ inputs.ksu_commit }}" ]; then
               curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/stable/kernel/setup.sh" | bash -s "${{ inputs.ksu_commit }}"
             else
@@ -340,6 +347,9 @@ jobs:
               if [ "$ACTUAL_SUBLEVEL" -le 41 ]; then
                 cp $KERNEL_PATCHES/wild/susfs_fix_patches/v${SUSFS_VERSION}/a13-5.15/open.c.patch ./
                 patch -p1 < open.c.patch
+              fi
+              if [ "$ACTUAL_SUBLEVEL" -le 41 ]; then
+                sed -i 's|is_i_uid_not_allowed(i_uid_into_mnt(i_user_ns(inode), inode).val)))|is_i_uid_not_allowed(inode->i_uid.val)))|g' fs/susfs.c
               fi
               if [[ "$ACTUAL_SUBLEVEL" -le 148 && "${{ inputs.os_patch_level }}" != "2024-05" ]]; then
                 sed -i -e 's/goto show_pad;/return 0;/' ./fs/proc/task_mmu.c
